**NUMPY**

In [1]:
%pip install numpy


   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
    --------------------------------------- 0.3/12.4 MB ? eta -:--:--
   --- ------------------------------------ 1.0/12.4 MB 3.7 MB/s eta 0:00:04
   ----- ---------------------------------- 1.8/12.4 MB 3.5 MB/s eta 0:00:04
   -------- ------------------------------- 2.6/12.4 MB 3.4 MB/s eta 0:00:03
   ---------- ----------------------------- 3.4/12.4 MB 3.5 MB/s eta 0:00:03
   ----------- ---------------------------- 3.7/12.4 MB 3.5 MB/s eta 0:00:03
   ----------- ---------------------------- 3.7/12.4 MB 3.5 MB/s eta 0:00:03
   ----------- ---------------------------- 3.7/12.4 MB 3.5 MB/s eta 0:00:03
   ------------ --------------------------- 3.9/12.4 MB 2.2 MB/s eta 0:00:04
   ------------- -------------------------- 4.2/12.4 MB 2.0 MB/s eta 0:00:05
   --------------- --------


[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
mylist = [1,2,3]

In [4]:
type (mylist)

list

In [5]:
np.array(mylist)

array([1, 2, 3])

In [6]:
mylist

[1, 2, 3]

In [7]:
myarr = np.array(mylist)

In [8]:
type(myarr)

numpy.ndarray

In [9]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [10]:
np.array (my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [16]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [18]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [3]:
st = 'hello my name is Markie - The Erasmus Mundus Scholar'

In [4]:
st.lower()

'hello my name is markie - the erasmus mundus scholar'

In [5]:
st.upper()

'HELLO MY NAME IS MARKIE - THE ERASMUS MUNDUS SCHOLAR'

In [6]:
st.split()

['hello',
 'my',
 'name',
 'is',
 'Markie',
 '-',
 'The',
 'Erasmus',
 'Mundus',
 'Scholar']

In [9]:

tweet = 'Go Markie! #Scholarship'

In [10]:

tweet.split('#')

['Go Markie! ', 'Scholarship']

In [11]:

tweet.split('#')[1]

'Scholarship'